version: 0.2
env:
  variables:
    AMI_FILTER: "amzn-ami-hvm-*-x86_64-gp2"
    AMI_PREFIX: "amazon-linux-ansible-packer"
    OS_VERSION: "Amazon Linux Base AMI"
    PACKER_VERSION: 1.1.3
    USER: root
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install openssl libcurl4-openssl-dev curl ssh -y
      - pip install pip -U && pip install -r pipeline/requirements.txt
      - echo "Installing HashiCorp Packer..."
      - mkdir .packer
      - curl -qL -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" && unzip packer.zip -d .packer/
      - chmod +x .packer/packer && mv .packer/packer /usr/local/bin/
  pre_build:
    commands:
      - echo "Configuring AWS credentials..."
      - aws configure set region $AWS_REGION
  build:
    commands:
      - packer validate packer/linux_aws_ansible_pipeline.json && PACKER_LOG=1 packer build packer/linux_aws_ansible_pipeline.json  | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id
      - test -s ami_id || exit 1

cache:
  paths:
    - '/root/.cache/pip/*'

artifacts:
  files:
    - ami_id
  discard-paths: yes
